import {
  Container,
  Typography
} from '@mui/material'
import { Box } from '@mui/system'
import { MainLayout } from 'components/layouts'
import SortChart from 'components/UI/SortView'
import React, { useRef, useState } from 'react'
import { useEffect } from 'react'
import { NextPageWithLayout } from './_app'
import { useSort } from 'context/sortMethods'
import Head from 'next/head'
import Image from "next/image";

const AnimationPage: NextPageWithLayout = () => {
  //context
  const {
    state: { title, methodAnimation }
  } = useSort()

  
  return (
    <>
    <Head>
        <title>Shellsort</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=Roboto+Mono:wght@300;500;700&display=swap" rel="stylesheet" />
      </Head>
    <Container sx={{ py: 10}}>
      <Typography textAlign="center" variant="h3" fontWeight="bold" mb={4} sx={{fontFamily: "Roboto Mono", letterSpacing: "8px", fontSize: "60px"}}>
        Funcionamiento {title}
      </Typography>
      {title === "Shellsort" 
      ? ( <Image src={require('/public/Shell_Sort.gif')} width={1200} height={700} alt={"Shell sort"} style={{borderRadius: "30px"}} /> ) 
      : title == "Bubblesort" 
      ? ( <Image src={require('/public/bubble.gif')} width={1200} height={700} alt={"Shell sort"} style={{borderRadius: "30px"}} /> )
      : 
       ( <Image src={require('/public/quick.gif')} width={1200} height={700} alt={"Shell sort"} style={{borderRadius: "30px"}} /> )
      }
    </Container></>
    
  )
}

AnimationPage.getLayout = (page: any) => {
  return (
    <MainLayout
      title="Animacion"
      description="Animacion de algoritmos de ordenamiento"
    >
      {page}
    </MainLayout>
  )
}

export default AnimationPage
